modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mixins]]
config = "lichenhistorycli.neoforge.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = "Bash-like history command management for Minecraft."
authors = "anjisuan608"
credits = "luosangguichen"
iconFile = "icon.png"
logoFile = "icon.png"
